version: "3.4"

services:
    backend:
        container_name: coin_master_backend
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        stdin_open: true
        volumes:
            - .:/home/elixir/backend
        # command: iex -S mix phx.server
        ports:
            - "4000:4000"
        env_file:
            - .env.dev
